version: "2"

services:
  db:
    container_name: gungnir-test
    image: postgres:14.4-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "9724:5432"
    expose:
      - 5432

  db2:
    container_name: gungnir-test-2
    image: postgres:14.4-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "9725:5432"
    expose:
      - 5432
