name: Test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Use oxr463/setup-leiningen
        uses: oxr463/setup-leiningen@0.0.1
        with:
          exec: |
            lein uberjar && \
            cp "$(find . -name '*.jar')" .

      - name: Setup Test Database
        run: docker-compose up -d

      - name: Check dependencies
        run: lein ancient

      - name: test
        run: lein cloverage --codecov
